# Individual tree point processing parameters (LAD/BAD generation)

trees:
    lad_reduction: 1.0    # coefficient for reduction of LAD in winter
    bad_coef: 0.1         # coefficient for reduction of BAD from LAD to account branches
    nhv: 10               # number of discretization layers for calculation of tree vertical shapes
    nump: 10              # number of polygon edges for interpolation of cycles for treetops and tree trunks
    ext_coef: 0.6         # Extinction coefficient (same as in PALM code) for tree crown transmissivity

canopy:
    using_lai: False
    lai_mod: 1.0
    canopy_height_mod: 1.0
